from dotenv import load_dotenv
load_dotenv()

from app import app, db
from app.models import db, User, Artist, Album, Song, PlaylistSong, Playlist


with app.app_context():
    db.drop_all()
    db.create_all()

    user = User(user_name="Cole", first_name="Cole", last_name="Rutledge", email="cole@email.com",hashed_password="password1")
    user2 = User(user_name="Chris", first_name="Chris", last_name="T", email="chris@mail.com",hashed_password="password2")
    db.session.add(user)
    db.session.add(user2)
    Blink182 = Artist(name="blink-182",bio="One of the most prominent bands to emerge from the Southern California punk scene, blink-182 gained mainstream success in the early 2000s. Arriving in the wake of the pop-punk explosion set off by , blink-182 gained a large fan base with their hooky, high-energy songs. At a time when competition with teen pop and nu-metal was not unheard of, they broke through with their third album, 1999's Enema of the State, releasing a steady stream of hits, bolstered by humorous, tongue-in-cheek music videos that were popular in the waning days of MTV's musical programming.",image_url="https://i.scdn.co/image/345f0de2b6bdadd50e7b5236324e9d2d1253a7d1")
    Chance = Artist(name="Chance the Rapper",bio="Despite his evasion of stylistic pigeonholing and no label affiliation -- not even a major-bankrolled vanity imprint -- Chance the Rapper became one of the most significant artists to infiltrate the mainstream during the 2010s. Through several mixtapes, his output underwent a rapid evolution as he celebrated life and faith, mourned personal loss, and hit upon lighter everyday experiences with high-aptitude wordplay served with a variety of mostly genial styles.",image_url="https://i.scdn.co/image/0433f521b1fadf1d839b6e70c3914021f122901f")
    PostMalone = Artist(name="Post Malone",bio="Within five years of his debut, American rapper and singer/songwriter Post Malone went from genre novelty to certified superstar, amassing a string of Top Ten singles with a hybrid style that joined his unique vocal delivery, pained lyrics, and hip-hop production inspired as much by Tim McGraw and Kanye West. After the release of his 2015 quintuple-platinum single \"White Iverson\" off debut Stoney, he quickly ascended to the top of the pop mainstream in the late 2010s with a succession of multi-platinum hits that included chart-toppers \"Rockstar\" with  and \"Psycho\" with  from 2018's number one, Grammy-nominated album Beerbongs & Bentleys and the Grammy-nominated \"Sunflower\" with  from 2019's Hollywood's Bleeding.",image_url="https://i.scdn.co/image/93fec27f9aac86526b9010e882037afbda4e3d5f")
    Rage = Artist(name="Rage Against The Machine",bio="Outspoken firebrands and activists Rage Against the Machine educated masses of heavy music fans by injecting their bombastic Molotov cocktail of rap, hardcore punk, funk, and metal with a sobering dose of fiercely polemical, politically charged urgency. Crashing the mainstream in 1992 with \"Killing in the Name\" -- their sonic protest against police brutality and systemic racism -- the band planted their flag in the scene with their triple-platinum debut, Rage Against the Machine, which courted controversy with its graphic cover of a protesting, self-immolated Buddhist monk.",image_url="https://i.scdn.co/image/679859f2e86b8b6b5b6d2a728e410dd4fe4b4af6")
    db.session.add(Blink182)
    db.session.add(Chance)
    db.session.add(PostMalone)
    db.session.add(Rage)
    album = Album(title="Greatest Hits",artist_id=1,image_url="https://i.scdn.co/image/ab67616d00001e026da502e35a7a3e48de2b0f74")
    album2 = Album(title="Acid Rap",artist_id=2,image_url="https://i.scdn.co/image/ab67616d00001e02d95ab48a8a9de3c4a2cbfe80")
    album3 = Album(title="beerbongs & bentleys",artist_id=3,image_url="https://i.scdn.co/image/ab67616d00001e02b1c4b76e23414c9f20242268")
    album4 = Album(title="Rage Against The Machine",artist_id=4,image_url="https://i.scdn.co/image/ab67616d00001e0224f31a0a281320f0cec6f86f")
    db.session.add(album)
    db.session.add(album2)
    db.session.add(album3)
    db.session.add(album4)
    playlist = Playlist(name="Demo Playlist", description="A convenient list of tunes for the demo...",image_url="https://bit.ly/2XH6Mj2", user_id=1)
    playlist2 = Playlist(name="vibes", description="This is ANOTHER playlist on this application",image_url="Placeholder playlist Image", user_id=2)
    db.session.add(playlist)
    db.session.add(playlist2)
    song1 = Song(title="All the Small Things", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/all-the-small-things.mp3", song_length="02:47")
    song2 = Song(title="What's My Age Again?", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/whats-my-age-again.mp3", song_length="02:29")
    song3 = Song(title="I Miss You", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/i-miss-you.mp3", song_length="02:29")
    song4 = Song(title="First Date", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/first-date.mp3", song_length="02:51")
    song5 = Song(title="Feeling This", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/feeling-this.mp3", song_length="02:52")
    song6 = Song(title="Good Ass Intro", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/good-ass-intro.mp3", song_length="03:59")
    song7 = Song(title="Pusha Man", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/pusha-man.mp3", song_length="02:19")
    song8 = Song(title="Cocoa Butter Kisses", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/cocoa-butter-kisses.mp3", song_length="05:07")
    song9 = Song(title="Smoke Again", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/smoke-again.mp3", song_length="04:33")
    song10 = Song(title="Acid Rain", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/acid-rain.mp3", song_length="03:36")
    song11 = Song(title="rockstar", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/rockstar.mp3", song_length="03:38")
    song12 = Song(title="Psycho", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/psycho.mp3", song_length="03:41")
    song13 = Song(title="Better Now", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/better-now.mp3", song_length="02:56")
    song14 = Song(title="Otherside", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/otherside.mp3", song_length="03:48")
    song15 = Song(title="Candy Paint", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/candy-paint.mp3", song_length="03:48")
    song16 = Song(title="Bombtrack", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/bombtrack.mp3", song_length="04:03")
    song17 = Song(title="Killing in the Name", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/killing-in-the-name.mp3", song_length="05:13")
    song18 = Song(title="Take the Power Back", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/take-the-power-back.mp3", song_length="05:36")
    song19 = Song(title="Settle for Nothing", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/settle-for-nothing.mp3", song_length="04:47")
    song20 = Song(title="Bullet in the Head", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/bullet-in-the-head.mp3", song_length="05:07")
    db.session.add(song1)
    db.session.add(song2)
    db.session.add(song3)
    db.session.add(song4)
    db.session.add(song5)
    db.session.add(song6)
    db.session.add(song7)
    db.session.add(song8)
    db.session.add(song9)
    db.session.add(song10)
    db.session.add(song11)
    db.session.add(song12)
    db.session.add(song13)
    db.session.add(song14)
    db.session.add(song15)
    db.session.add(song16)
    db.session.add(song17)
    db.session.add(song18)
    db.session.add(song19)
    db.session.add(song20)
    db.session.commit()
    playlistsong = PlaylistSong(playlist_id=1,song_id=1)
    playlistsong2 = PlaylistSong(playlist_id=1,song_id=8)
    playlistsong3 = PlaylistSong(playlist_id=1,song_id=12)
    playlistsong4 = PlaylistSong(playlist_id=1,song_id=16)
    playlistsong5 = PlaylistSong(playlist_id=2,song_id=2)
    db.session.add(playlistsong)
    db.session.add(playlistsong2)
    db.session.add(playlistsong3)
    db.session.add(playlistsong4)
    db.session.add(playlistsong5)
    db.session.commit()

    YoungTheGiant = Artist(name=" Young the Giant",bio="Los Angeles quintet Young the Giant expertly juxtapose their adventurous spirit with fearless grace on their new album, Mirror Master. Featuring their new single “Superposition,” the band’s fourth studio LP follows 2016's critically acclaimed Home of the Strange.",image_url="https://i.scdn.co/image/61e914d1538bf9a0e1869f3e41e649d9b012c60a")
    db.session.add(YoungTheGiant)
    album5 = Album(title="Mirror Master",artist_id=5,image_url="https://i.scdn.co/image/ab67616d00001e021cce1764a83486d563410c5a")
    db.session.add(album5)
    song21 = Song(title="Superposition", album_id = 5, song_url="this is the song url", song_length="03:50")
    song22 = Song(title="Simplify", album_id = 5, song_url="this is the song url", song_length="03:32")
    song23 = Song(title="Call Me Back", album_id = 5, song_url="this is the song url", song_length="03:57")
    song24 = Song(title="Heat of the Summer", album_id = 5, song_url="this is the song url", song_length="03:31")
    song25 = Song(title="Oblivion", album_id = 5, song_url="this is the song url", song_length="03:48")
    song26 = Song(title="Darkest Shade of Blue", album_id = 5, song_url="this is the song url", song_length="02:13")
    song27 = Song(title="Brother's Keeper", album_id = 5, song_url="this is the song url", song_length="04:10")
    song28 = Song(title="Glory", album_id = 5, song_url="this is the song url", song_length="03:18")
    song29 = Song(title="Tightrope", album_id = 5, song_url="this is the song url", song_length="03:58")
    song30 = Song(title="Panoramic Girl", album_id = 5, song_url="this is the song url", song_length="04:02")
    song31 = Song(title="You + I", album_id = 5, song_url="this is the song url", song_length="04:14")
    song32 = Song(title="Mirror Master", album_id = 5, song_url="this is the song url", song_length="04:09")
    db.session.add(song21)
    db.session.add(song22)
    db.session.add(song23)
    db.session.add(song24)
    db.session.add(song25)
    db.session.add(song26)
    db.session.add(song27)
    db.session.add(song28)
    db.session.add(song29)
    db.session.add(song30)
    db.session.add(song31)
    db.session.add(song32)
    db.session.commit()

    Logic = Artist(name="Logic",bio="The stylistically dynamic and voluble Logic launched his rap career through uploads and mixtapes prior to signing a deal that fostered a sustained mainstream presence throughout the second half of the 2010s.",image_url="https://i.scdn.co/image/0caa5d73bd4ffa679036cf701507adc4d363478d")
    db.session.add(Logic)
    album6 = Album(title="No Pressure",artist_id=6,image_url="https://i.scdn.co/image/ab67616d00001e021c76e29153f29cc1e1b2b434")
    db.session.add(album6)
    song33 = Song(title="No Pressure Intro", album_id = 6, song_url="this is the song url", song_length="02:54")
    song34 = Song(title="Hit My Line", album_id = 6, song_url="this is the song url", song_length="04:25")
    song35 = Song(title="GP4", album_id = 6, song_url="this is the song url", song_length="04:25")
    song36 = Song(title="Celebration", album_id = 6, song_url="this is the song url", song_length="03:50")
    song37 = Song(title="Open Mic\\Aquarius III", album_id = 6, song_url="this is the song url", song_length="5:03")
    song38 = Song(title="Soul Food II", album_id = 6, song_url="this is the song url", song_length="05:33")
    song39 = Song(title="Perfect", album_id = 6, song_url="this is the song url", song_length="01:40")
    song40 = Song(title="man i is", album_id = 6, song_url="this is the song url", song_length="04:29")
    song41 = Song(title="DadBod", album_id = 6, song_url="this is the song url", song_length="04:54")
    song42 = Song(title="5 Hooks", album_id = 6, song_url="this is the song url", song_length="03:52")
    song43 = Song(title="Dark Place", album_id = 6, song_url="this is the song url", song_length="03:15")
    song44 = Song(title="A2Z", album_id = 6, song_url="this is the song url", song_length="03:08")
    song45 = Song(title="Heard Em Say", album_id = 6, song_url="this is the song url", song_length="03:36")
    song46 = Song(title="Amen", album_id = 6, song_url="this is the song url", song_length="02:26")
    song47 = Song(title="Obediently Yours", album_id = 6, song_url="this is the song url", song_length="06:09")
    db.session.add(song33)
    db.session.add(song34)
    db.session.add(song35)
    db.session.add(song36)
    db.session.add(song36)
    db.session.add(song38)
    db.session.add(song39)
    db.session.add(song40)
    db.session.add(song41)
    db.session.add(song42)
    db.session.add(song43)
    db.session.add(song44)
    db.session.add(song45)
    db.session.add(song46)
    db.session.add(song47)

    TheWeeknd = Artist(name="The Weeknd",bio="The Weeknd took over pop music & culture on his own terms filtering R&B, Pop,& hip-hop through an ambitious widescreen lens.",image_url="https://i.scdn.co/image/91c55730d3f156894d744d560afe441af3f5a228")
    db.session.add(TheWeeknd)
    album7 = Album(title="After Hours",artist_id=7,image_url="https://i.scdn.co/image/ab67616d00001e028863bc11d2aa12b54f5aeb36")
    db.session.add(album7)
    song48 = Song(title="Alone Again", album_id = 7, song_url="this is the song url", song_length="04:10")
    song49 = Song(title="Too Late", album_id = 7, song_url="this is the song url", song_length="03:59")
    song50 = Song(title="Hardest To Love", album_id = 7, song_url="this is the song url", song_length="03:31")
    song51 = Song(title="Scared To Live", album_id = 7, song_url="this is the song url", song_length="03:11")
    song52 = Song(title="Snowchild", album_id = 7, song_url="this is the song url", song_length="04:07")
    song53 = Song(title="Escape From LA", album_id = 7, song_url="this is the song url", song_length="05:55")
    song54 = Song(title="Heartless", album_id = 7, song_url="this is the song url", song_length="03:18")
    song55 = Song(title="Faith", album_id = 7, song_url="this is the song url", song_length="04:43")
    song56 = Song(title="Blinding Lights", album_id = 7, song_url="this is the song url", song_length="03:20")
    song57 = Song(title="In Your Eyes", album_id = 7, song_url="this is the song url", song_length="03:57")
    song58 = Song(title="Save Your Tears", album_id = 7, song_url="this is the song url", song_length="03:35")
    song59 = Song(title="Repeat After Me (Interlude)", album_id = 7, song_url="this is the song url", song_length="03:15")
    song60 = Song(title="After Hours", album_id = 7, song_url="this is the song url", song_length="06:01")
    song61 = Song(title="Until I Bleed Out", album_id = 7, song_url="this is the song url", song_length="03:10")
    db.session.add(song48)
    db.session.add(song49)
    db.session.add(song50)
    db.session.add(song51)
    db.session.add(song52)
    db.session.add(song53)
    db.session.add(song54)
    db.session.add(song55)
    db.session.add(song56)
    db.session.add(song57)
    db.session.add(song58)
    db.session.add(song59)
    db.session.add(song60)
    db.session.add(song61)

    BillieEilish = Artist(name="Billie Eilish",bio="18-year-old global pop-phenom Billie Eilish has fast become one of the biggest stars to emerge since the release of her debut single “ocean eyes,” and continues to shatter the ceiling of music with her genre-defying sound.",image_url="https://i.scdn.co/image/dc74e8e210274fd6107a795db2455c1e03730667")
    db.session.add(BillieEilish)
    album8 = Album(title="WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",artist_id=8,image_url="https://i.scdn.co/image/ab67616d00001e0250a3147b4edd7701a876c6ce")
    db.session.add(album8)
    song62 = Song(title="!!!!!!!", album_id = 8, song_url="this is the song url", song_length="00:13")
    song63 = Song(title="bad guy", album_id = 8, song_url="this is the song url", song_length="03:14")
    song64 = Song(title="xanny", album_id = 8, song_url="this is the song url", song_length="04:03")
    song65 = Song(title="you should see me in a crown", album_id = 8, song_url="this is the song url", song_length="03:00")
    song66 = Song(title="all the good girls go to hell", album_id = 8, song_url="this is the song url", song_length="02:48")
    song67 = Song(title="wish you were gay", album_id = 8, song_url="this is the song url", song_length="03:41")
    song68 = Song(title="when the party's over", album_id = 8, song_url="this is the song url", song_length="03:16")
    song69 = Song(title="8", album_id = 8, song_url="this is the song url", song_length="02:53")
    song70 = Song(title="my strange addiction", album_id = 8, song_url="this is the song url", song_length="02:59")
    song71 = Song(title="bury a friend", album_id = 8, song_url="this is the song url", song_length="03:13")
    song72 = Song(title="ilomilo", album_id = 8, song_url="this is the song url", song_length="02:36")
    song73 = Song(title="listen before i go", album_id = 8, song_url="this is the song url", song_length="04:02")
    song74 = Song(title="i love you", album_id = 8, song_url="this is the song url", song_length="04:51")
    song75 = Song(title="goodbye", album_id = 8, song_url="this is the song url", song_length="01:59")
    db.session.add(song62)
    db.session.add(song63)
    db.session.add(song64)
    db.session.add(song65)
    db.session.add(song66)
    db.session.add(song67)
    db.session.add(song68)
    db.session.add(song69)
    db.session.add(song70)
    db.session.add(song71)
    db.session.add(song72)
    db.session.add(song73)
    db.session.add(song74)
    db.session.add(song75)

    ArianaGrande = Artist(name="Ariana Grande",bio="Ariana Grande is perhaps the quintessential pop star of the last half of the 2010s, capturing the era's spirit and style.",image_url="https://i.scdn.co/image/b189cb24f45db92780d1aa6c81aee69b8defa03a")
    db.session.add(ArianaGrande)
    album9 = Album(title="thank u, next",artist_id=9,image_url="https://i.scdn.co/image/ab67616d00001e0256ac7b86e090f307e218e9c8")
    db.session.add(album9)
    song76 = Song(title="imagine", album_id = 9, song_url="this is the song url", song_length="03:32")
    song77 = Song(title="needy", album_id = 9, song_url="this is the song url", song_length="02:51")
    song78 = Song(title="NASA", album_id = 9, song_url="this is the song url", song_length="03:02")
    song79 = Song(title="bloodline", album_id = 9, song_url="this is the song url", song_length="03:36")
    song80 = Song(title="fake smile", album_id = 9, song_url="this is the song url", song_length="03:28")
    song81 = Song(title="bad idea", album_id = 9, song_url="this is the song url", song_length="04:27")
    song82 = Song(title="make up", album_id = 9, song_url="this is the song url", song_length="02:20")
    song83 = Song(title="ghostin", album_id = 9, song_url="this is the song url", song_length="04:31")
    song84 = Song(title="in my head", album_id = 9, song_url="this is the song url", song_length="03:42")
    song85 = Song(title="7 rings", album_id = 9, song_url="this is the song url", song_length="02:58")
    song86 = Song(title="thank u, next", album_id = 9, song_url="this is the song url", song_length="03:27")
    song87 = Song(title="break up with your girlfriend, i'm bored", album_id = 9, song_url="this is the song url", song_length="03:10")
    db.session.add(song76)
    db.session.add(song77)
    db.session.add(song78)
    db.session.add(song79)
    db.session.add(song80)
    db.session.add(song81)
    db.session.add(song82)
    db.session.add(song83)
    db.session.add(song84)
    db.session.add(song85)
    db.session.add(song86)
    db.session.add(song87)

    LadyGaga = Artist(name="Lady Gaga",bio="Academy Award, Golden Globe & Grammy-winner Lady Gaga is a one-of-a kind artist and performer.",image_url="https://i.scdn.co/image/22e5bd06cd56f4bc430e0d4eb95af75565fdffa8")
    db.session.add(LadyGaga)
    album10 = Album(title="Chromatica",artist_id=10,image_url="https://i.scdn.co/image/ab67616d00001e026040effba89b9b00a6f6743a")
    db.session.add(album10)
    song88 = Song(title="Chromatica I", album_id = 10, song_url="this is the song url", song_length="01:00")
    song89 = Song(title="Alice", album_id = 10, song_url="this is the song url", song_length="02:57")
    song90 = Song(title="Stupid Love", album_id = 10, song_url="this is the song url", song_length="03:13")
    song91 = Song(title="Rain On Me (with Ariana Grande)", album_id = 10, song_url="this is the song url", song_length="03:02")
    song92 = Song(title="Free Woman", album_id = 10, song_url="this is the song url", song_length="03:11")
    song93 = Song(title="Fun Tonight", album_id = 10, song_url="this is the song url", song_length="02:53")
    song94 = Song(title="Chromatica II", album_id = 10, song_url="this is the song url", song_length="00:41")
    song95 = Song(title="911", album_id = 10, song_url="this is the song url", song_length="02:52")
    song96 = Song(title="Plastic Doll", album_id = 10, song_url="this is the song url", song_length="03:41")
    song97 = Song(title="Sour Candy (with BLACKPINK)", album_id = 10, song_url="this is the song url", song_length="02:37")
    song98 = Song(title="Enigma", album_id = 10, song_url="this is the song url", song_length="02:59")
    song99 = Song(title="Replay", album_id = 10, song_url="this is the song url", song_length="03:06")
    song100 = Song(title="Chromatica III", album_id = 10, song_url="this is the song url", song_length="00:27")
    song101 = Song(title="Sine From Above (with Elton John)", album_id = 10, song_url="this is the song url", song_length="04:04")
    song102 = Song(title="1000 Doves", album_id = 10, song_url="this is the song url", song_length="03:35")
    song103 = Song(title="Babylon", album_id = 10, song_url="this is the song url", song_length="02:41")
    db.session.add(song88)
    db.session.add(song89)
    db.session.add(song90)
    db.session.add(song91)
    db.session.add(song92)
    db.session.add(song93)
    db.session.add(song94)
    db.session.add(song95)
    db.session.add(song96)
    db.session.add(song97)
    db.session.add(song98)
    db.session.add(song99)
    db.session.add(song100)
    db.session.add(song101)
    db.session.add(song102)
    db.session.add(song103)

    FleetwoodMac = Artist(name="Fleetwood Mac",bio="While most bands undergo a number of changes over the course of their careers, few groups experienced such radical stylistic changes as Fleetwood Mac. Initially conceived as a hard-edged British blues combo in the late '60s, the band gradually evolved into a polished pop/rock act over the course of a decade.",image_url="https://i.scdn.co/image/7316c71bf06332dc259e14ddce420b2b060e9c69")
    db.session.add(FleetwoodMac)
    album11 = Album(title="Rumours(Super Deluxe)",artist_id=11,image_url="https://i.scdn.co/image/ab67616d00001e02e52a59a28efa4773dd2bfe1b")
    db.session.add(album11)
    song104 = Song(title="Second Hand News", album_id = 11, song_url="this is the song url", song_length="02:56")
    song105 = Song(title="Dreams", album_id = 11, song_url="this is the song url", song_length="04:17")
    song106 = Song(title="Never Going Back Again", album_id = 11, song_url="this is the song url", song_length="02:14")
    song107 = Song(title="Don't Stop", album_id = 11, song_url="this is the song url", song_length="03:13")
    song108 = Song(title="Go Your Own Way", album_id = 11, song_url="this is the song url", song_length="03:43")
    db.session.add(song104)
    db.session.add(song105)
    db.session.add(song106)
    db.session.add(song107)
    db.session.add(song108)

    SylvanEsso = Artist(name="Sylvan Esso",bio="Sitting in a Wisconsin deli in 2012, Amelia Meath told her new friend Nick Sanborn she wanted to start a pop band.",image_url="https://i.scdn.co/image/9ea9bfbe76357be12ac180927246a9279375afa9")
    db.session.add(SylvanEsso)
    album12 = Album(title="Sylvan Esso",artist_id=12,image_url="https://i.scdn.co/image/ab67616d00001e02ea6019a29888aaba30f440db")
    db.session.add(album12)
    song109 = Song(title="Hey Mami", album_id = 12, song_url="this is the song url", song_length="03:20")
    song110 = Song(title="Dreamy Bruises", album_id = 12, song_url="this is the song url", song_length="04:08")
    song111 = Song(title="Could I Be", album_id = 12, song_url="this is the song url", song_length="04:39")
    song112 = Song(title="Wolf", album_id = 12, song_url="this is the song url", song_length="03:15")
    song113 = Song(title="Dress", album_id = 12, song_url="this is the song url", song_length="03:49")
    db.session.add(song109)
    db.session.add(song110)
    db.session.add(song111)
    db.session.add(song112)
    db.session.add(song113)

    AlabamaShakes = Artist(name="Alabama Shakes",bio="Muscle Shoals-inspired, Athens, Alabama-based quartet Alabama Shakes formed in 2009 around the talents of Brittany Howard, Zac Cockrell, Steve Johnson, and Heath Fogg.",image_url="https://i.scdn.co/image/636403b45a4a5dedb85fa14ab58f3ca66d98cc91")
    db.session.add(AlabamaShakes)
    album13 = Album(title="Sound & Color",artist_id=13,image_url="https://i.scdn.co/image/ab67616d00001e02732af53fdad3318e347bc942")
    db.session.add(album13)
    song114 = Song(title="Sound & Color", album_id = 13, song_url="this is the song url", song_length="03:03")
    song115 = Song(title="Don't Wanna Fight", album_id = 13, song_url="this is the song url", song_length="03:52")
    song116 = Song(title="Dunes", album_id = 13, song_url="this is the song url", song_length="04:17")
    song117 = Song(title="Future People", album_id = 13, song_url="this is the song url", song_length="03:21")
    song118 = Song(title="Gimme All Your Love", album_id = 13, song_url="this is the song url", song_length="04:03")
    db.session.add(song114)
    db.session.add(song115)
    db.session.add(song116)
    db.session.add(song117)
    db.session.add(song118)

    Halsey = Artist(name="Halsey",bio="Halsey is the alias of New York-based pop singer Ashley Frangipane. The New Jersey native took her moniker from a New York L train subway stop, and her adopted city plays a large role in both the sound and lyrics of her dark, gritty electro-pop.",image_url="https://i.scdn.co/image/8b56979f115e855301c33828bcad2c57280adbab")
    db.session.add(Halsey)
    album14 = Album(title="Manic",artist_id=14,image_url="https://i.scdn.co/image/ab67616d00001e027636e1c9e67eaafc9f49aefd")
    db.session.add(album14)
    song119 = Song(title="Ashley", album_id = 14, song_url="this is the song url", song_length="03:06")
    song120 = Song(title="clementine", album_id = 14, song_url="this is the song url", song_length="03:54")
    song121 = Song(title="Graveyard", album_id = 14, song_url="this is the song url", song_length="03:01")
    song122 = Song(title="You should be sad", album_id = 14, song_url="this is the song url", song_length="03:25")
    song123 = Song(title="Forever...(is a long time)", album_id = 14, song_url="this is the song url", song_length="02:47")
    db.session.add(song119)
    db.session.add(song120)
    db.session.add(song121)
    db.session.add(song122)
    db.session.add(song123)

    Lizzo = Artist(name="Lizzo",bio="Combining her roots in Houston rap, gospel soul, and classical flute as confidently as she addresses issues of race, sexuality, and body positivity, singer/rapper Lizzo's music abounds with humor and charisma.",image_url="https://i.scdn.co/image/4f9987e4ab87fc44cb3136b7aea0ec3ad003ccd2")
    db.session.add(Lizzo)
    album15 = Album(title="Cuz I Love You",artist_id=15,image_url="https://i.scdn.co/image/ab67616d00001e0206af802e2ea241b6ba1ce0f2")
    db.session.add(album15)
    song124 = Song(title="Cuz I Love You", album_id = 15, song_url="this is the song url", song_length="02:59")
    song125 = Song(title="Like a Girl", album_id = 15, song_url="this is the song url", song_length="03:04")
    song126 = Song(title="Juice", album_id = 15, song_url="this is the song url", song_length="03:15")
    song127 = Song(title="Soulmate", album_id = 15, song_url="this is the song url", song_length="02:55")
    song128 = Song(title="Jerome", album_id = 15, song_url="this is the song url", song_length="03:51")
    song129 = Song(title="Crybaby", album_id = 15, song_url="this is the song url", song_length="02:55")
    db.session.add(song124)
    db.session.add(song125)
    db.session.add(song126)
    db.session.add(song127)
    db.session.add(song128)
    db.session.add(song129)

    Nirvana = Artist(name="Nirvana",bio="Prior to Nirvana, alternative music was consigned to specialty sections of record stores, and major labels considered it to be, at the very most, a tax write-off.",image_url="https://i.scdn.co/image/42ae0f180f16e2f21c1f2212717fc436f5b95451")
    db.session.add(Nirvana)
    album16 = Album(title="Nevermind",artist_id=16,image_url="https://i.scdn.co/image/ab67616d00001e02e175a19e530c898d167d39bf")
    db.session.add(album16)
    song130 = Song(title="Smells Like Teen Spirit", album_id = 16, song_url="this is the song url", song_length="05:01")
    song131 = Song(title="In Bloom - Nevermind Version", album_id = 16, song_url="this is the song url", song_length="04:15")
    song132 = Song(title="Come As You Are", album_id = 16, song_url="this is the song url", song_length="03:38")
    song133 = Song(title="Breed", album_id = 16, song_url="this is the song url", song_length="03:04")
    song134 = Song(title="Lithium", album_id = 16, song_url="this is the song url", song_length="04:17")
    db.session.add(song130)
    db.session.add(song131)
    db.session.add(song132)
    db.session.add(song133)
    db.session.add(song134)

    GreenDay = Artist(name="Green Day",bio="God's favorite band.",image_url="https://i.scdn.co/image/8e7cb070f12ae05f76711cf95487752a3f685465")
    db.session.add(GreenDay)
    album17 = Album(title="Dookie",artist_id=17,image_url="https://i.scdn.co/image/ab67616d00001e02db89b08034de626ebee6823d")
    db.session.add(album17)
    song135 = Song(title="Burnout", album_id = 17, song_url="this is the song url", song_length="02:07")
    song136 = Song(title="Having a Blast", album_id = 17, song_url="this is the song url", song_length="02:44")
    song137 = Song(title="Chump", album_id = 17, song_url="this is the song url", song_length="02:54")
    song138 = Song(title="Longview", album_id = 17, song_url="this is the song url", song_length="03:53")
    song139 = Song(title="Welcome to Paradise", album_id = 17, song_url="this is the song url", song_length="03:44")
    db.session.add(song135)
    db.session.add(song136)
    db.session.add(song137)
    db.session.add(song138)
    db.session.add(song139)

    TheNotoriousBig = Artist(name="The Notorious B.I.G.",bio="In just a few short years, the Notorious B.I.G. went from a Brooklyn street hustler to the savior of East Coast hip-hop to a tragic victim of the culture of violence he depicted so realistically on his records.",image_url="https://i.scdn.co/image/e56612ae56c9007e99ab36b83efd4faf6401260d")
    db.session.add(TheNotoriousBig)
    album18 = Album(title="Ready to Die(The Remaster)",artist_id=18,image_url="https://i.scdn.co/image/ab67616d00001e02a4950162a626593b7340f6c7")
    db.session.add(album18)
    song140 = Song(title="Intro", album_id = 18, song_url="this is the song url", song_length="03:23")
    song141 = Song(title="Things Done Changed", album_id = 18, song_url="this is the song url", song_length="03:58")
    song142 = Song(title="Gimme the Loot", album_id = 18, song_url="this is the song url", song_length="05:04")
    song143 = Song(title="Machine Gun Funk", album_id = 18, song_url="this is the song url", song_length="04:15")
    song144 = Song(title="Warning", album_id = 18, song_url="this is the song url", song_length="03:40")
    db.session.add(song140)
    db.session.add(song141)
    db.session.add(song142)
    db.session.add(song143)
    db.session.add(song144)

    YoungThug = Artist(name="Young Thug",bio="Flouting hip-hop conventions while defying gender and sexuality stereotypes, Young Thug has been one of the most distinctive contemporary rap artists since attaining his chart debut with \"Stoner\" (2014).",image_url="https://i.scdn.co/image/baa269702b35bf2eea6e04fa06f057c74ac96169")
    db.session.add(YoungThug)
    album19 = Album(title="JEFFERY",artist_id=19,image_url="https://i.scdn.co/image/ab67616d00001e02d0c72291cd96834e199e1ff8")
    db.session.add(album19)
    song145 = Song(title="Wyclef Jean", album_id = 19, song_url="this is the song url", song_length="03:56")
    song146 = Song(title="Floyd Mayweather (feat. Travis Scott, Gucci Mane and Gunna)", album_id = 19, song_url="this is the song url", song_length="05:58")
    song147 = Song(title="Swizz Beatz", album_id = 19, song_url="this is the song url", song_length="03:16")
    song148 = Song(title="Future Swag", album_id = 19, song_url="this is the song url", song_length="02:45")
    song149 = Song(title="RiRi", album_id = 19, song_url="this is the song url", song_length="04:04")
    db.session.add(song145)
    db.session.add(song146)
    db.session.add(song147)
    db.session.add(song148)
    db.session.add(song149)

    AmyWinehouse = Artist(name="Amy Winehouse",bio="Much can be said about the late Amy Winehouse, one of the U.K.'s flagship vocalists during the 2000s.",image_url="https://i.scdn.co/image/4b22b96a98eb664fe73c1c1cec9cf641f57b7c6f")
    db.session.add(AmyWinehouse)
    album20 = Album(title="Back to Black",artist_id=20,image_url="https://i.scdn.co/image/ab67616d00001e028f52f321140e4a76ea720c52")
    db.session.add(album20)
    song150 = Song(title="Rehab", album_id = 20, song_url="this is the song url", song_length="03:33")
    song151 = Song(title="You Know I'm No Good", album_id = 20, song_url="this is the song url", song_length="04:16")
    song152 = Song(title="Me & Mr Jones", album_id = 20, song_url="this is the song url", song_length="02:31")
    song153 = Song(title="Just Friends", album_id = 20, song_url="this is the song url", song_length="03:11")
    song154 = Song(title="Back To Black", album_id = 20, song_url="this is the song url", song_length="04:00")
    db.session.add(song150)
    db.session.add(song151)
    db.session.add(song152)
    db.session.add(song153)
    db.session.add(song154)

    album21 = Album(title="Stoney (Deluxe)",artist_id=3,image_url="https://i.scdn.co/image/ab67616d00001e0255404f712deb84d0650a4b41")
    song155 = Song(title="Broken Whiskey Glass", album_id = 21, song_url="this is the song url", song_length="03:53")
    song156 = Song(title="Big Lie", album_id = 21, song_url="this is the song url", song_length="03:27")
    song157 = Song(title="Deja Vu", album_id = 21, song_url="this is the song url", song_length="03:54")
    song158 = Song(title="No Option", album_id = 21, song_url="this is the song url", song_length="02:59")
    song159 = Song(title="Cold", album_id = 21, song_url="this is the song url", song_length="04:28")
    db.session.add(album21)
    db.session.add(song155)
    db.session.add(song156)
    db.session.add(song157)
    db.session.add(song158)
    db.session.add(song159)

    album22 = Album(title="10 Day",artist_id=2,image_url="https://i.scdn.co/image/ab67616d00001e024bbc300c4e9e8847ca1a2873")
    db.session.add(album22)
    song160 = Song(title="14,400 Minutes", album_id = 22, song_url="this is the song url", song_length="02:08")
    song161 = Song(title="Nostalgia", album_id = 22, song_url="this is the song url", song_length="03:23")
    song162 = Song(title="Missing You", album_id = 22, song_url="this is the song url", song_length="03:24")
    song163 = Song(title="Windows", album_id = 22, song_url="this is the song url", song_length="02:55")
    song164 = Song(title="Brain Cells", album_id = 22, song_url="this is the song url", song_length="04:52")
    db.session.add(song160)
    db.session.add(song161)
    db.session.add(song162)
    db.session.add(song163)
    db.session.add(song164)

    album23 = Album(title="Buddha",artist_id=1,image_url="https://i.scdn.co/image/ab67616d00001e023d3b60439616a720ee90b464")
    db.session.add(album23)
    song165 = Song(title="Carousel", album_id = 23, song_url="this is the song url", song_length="02:40")
    song166 = Song(title="T.V.", album_id = 23, song_url="this is the song url", song_length="01:37")
    song167 = Song(title="String", album_id = 23, song_url="this is the song url", song_length="02:28")
    song168 = Song(title="Fentoozler", album_id = 23, song_url="this is the song url", song_length="02:03")
    song169 = Song(title="Time", album_id = 23, song_url="this is the song url", song_length="02:46")
    db.session.add(song165)
    db.session.add(song166)
    db.session.add(song167)
    db.session.add(song168)
    db.session.add(song169)

    album24 = Album(title="Dude Ranch",artist_id=1,image_url="https://i.scdn.co/image/ab67616d00001e02330500a40905b093b134396a")
    db.session.add(album24)
    song170 = Song(title="Pathetic", album_id = 24, song_url="this is the song url", song_length="02:28")
    song171 = Song(title="Voyeur", album_id = 24, song_url="this is the song url", song_length="02:43")
    song172 = Song(title="Dammit", album_id = 24, song_url="this is the song url", song_length="02:45")
    song173 = Song(title="Boring", album_id = 24, song_url="this is the song url", song_length="01:41")
    song174 = Song(title="Dick Lips", album_id = 24, song_url="this is the song url", song_length="02:57")
    db.session.add(song170)
    db.session.add(song171)
    db.session.add(song172)
    db.session.add(song173)
    db.session.add(song174)

    album25 = Album(title="Evil Empire",artist_id=4,image_url="https://i.scdn.co/image/ab67616d00001e02053f006079bce979e5fef1e1")
    db.session.add(album25)
    song175 = Song(title="People of the Sun", album_id = 25, song_url="this is the song url", song_length="02:30")
    song176 = Song(title="Bulls On Parade", album_id = 25, song_url="this is the song url", song_length="03:49")
    song177 = Song(title="Vietnow", album_id = 25, song_url="this is the song url", song_length="04:37")
    song178 = Song(title="Revolver", album_id = 25, song_url="this is the song url", song_length="05:27")
    song179 = Song(title="Snakecharmer", album_id = 25, song_url="this is the song url", song_length="03:55")
    db.session.add(song175)
    db.session.add(song176)
    db.session.add(song177)
    db.session.add(song178)
    db.session.add(song179)

    album26 = Album(title="The Battle Of Los Angeles",artist_id=4,image_url="https://i.scdn.co/image/ab67616d00001e023c2579a4f8cacd5b95b8fa68")
    db.session.add(album26)
    song180 = Song(title="Testify", album_id = 26, song_url="this is the song url", song_length="03:30")
    song181 = Song(title="Guerrilla Radio", album_id = 26, song_url="this is the song url", song_length="03:26")
    song182 = Song(title="Calm Like a Bomb", album_id = 26, song_url="this is the song url", song_length="04:58")
    song183 = Song(title="Mic Check", album_id = 26, song_url="this is the song url", song_length="03:33")
    song184 = Song(title="Sleep Now In the Fire", album_id = 26, song_url="this is the song url", song_length="03:25")
    db.session.add(song180)
    db.session.add(song181)
    db.session.add(song182)
    db.session.add(song183)
    db.session.add(song184)
    db.session.commit()
