from dotenv import load_dotenv
load_dotenv()

from app import app, db
from app.models import db, User, Artist, Album, Song, PlaylistSong, Playlist


with app.app_context():
    db.drop_all()
    db.create_all()

    user = User(user_name="Test", first_name="testOne", last_name="1", email="test@email.com",hashed_password="password1")
    user2 = User(user_name="Test Two", first_name="testTwo", last_name="2", email="test@mail.com",hashed_password="password2")
    db.session.add(user)
    db.session.add(user2)
    Blink182 = Artist(name="Blink-182",bio="One of the most prominent bands to emerge from the Southern California punk scene, blink-182 gained mainstream success in the early 2000s",image_url="https://i.scdn.co/image/345f0de2b6bdadd50e7b5236324e9d2d1253a7d1")
    Chance = Artist(name="Chance the Rapper",bio="Despite his evasion of stylistic pigeonholing and no label affiliation -- not even a major-bankrolled vanity imprint -- Chance the Rapper became one of the most significant artists to infiltrate the mainstream during the 2010s. ",image_url="https://i.scdn.co/image/0433f521b1fadf1d839b6e70c3914021f122901f")
    PostMalone = Artist(name="Post Malone",bio="Within five years of his debut, American rapper and singer/songwriter Post Malone went from genre novelty to certified superstar, amassing a string of Top Ten singles with a hybrid style that joined his unique vocal delivery, pained lyrics, and hip-hop production inspired as much by Tim McGraw and Kanye West",image_url="https://i.scdn.co/image/93fec27f9aac86526b9010e882037afbda4e3d5f")
    Rage = Artist(name="Rage Against The Machine",bio="Outspoken firebrands and activists Rage Against the Machine educated masses of heavy music fans by injecting their bombastic Molotov cocktail of rap, hardcore punk, funk, and metal with a sobering dose of fiercely polemical, politically charged urgency.",image_url="https://i.scdn.co/image/679859f2e86b8b6b5b6d2a728e410dd4fe4b4af6")
    db.session.add(Blink182)
    db.session.add(Chance)
    db.session.add(PostMalone)
    db.session.add(Rage)
    album = Album(title="Greatest Hits",artist_id=1,image_url="https://i.scdn.co/image/ab67616d00001e026da502e35a7a3e48de2b0f74")
    album2 = Album(title="Acid Rap",artist_id=2,image_url="https://i.scdn.co/image/ab67616d00001e02d95ab48a8a9de3c4a2cbfe80")
    album3 = Album(title="beerbongs & bentleys",artist_id=3,image_url="https://i.scdn.co/image/ab67616d00001e02b1c4b76e23414c9f20242268")
    album4 = Album(title="Rage Against The Machine",artist_id=4,image_url="https://i.scdn.co/image/ab67616d00001e0224f31a0a281320f0cec6f86f")
    db.session.add(album)
    db.session.add(album2)
    db.session.add(album3)
    db.session.add(album4)
    playlist = Playlist(name="My First Playlist", description="This is my first playlist on this application",image_url="Placeholder playlist Image", user_id=1)
    playlist2 = Playlist(name="My Second Playlist", description="This is ANOTHER playlist on this application",image_url="Placeholder playlist Image", user_id=2)
    db.session.add(playlist)
    db.session.add(playlist2)
    song1 = Song(title="All the Small Things", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/all-the-small-things.mp3", song_length=180)
    song2 = Song(title="What's My Age Again?", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/whats-my-age-again.mp3", song_length=180)
    song3 = Song(title="I Miss You", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/i-miss-you.mp3", song_length=180)
    song4 = Song(title="First Date", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/first-date.mp3", song_length=180)
    song5 = Song(title="Feeling This", album_id = 1, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/feeling-this.mp3", song_length=180)
    song6 = Song(title="Good Ass Intro", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/good-ass-intro.mp3", song_length=180)
    song7 = Song(title="Pusha Man", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/pusha-man.mp3", song_length=180)
    song8 = Song(title="Cocoa Butter Kisses", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/cocoa-butter-kisses.mp3", song_length=180)
    song9 = Song(title="Smoke Again", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/smoke-again.mp3", song_length=180)
    song10 = Song(title="Acid Rain", album_id = 2, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/acid-rain.mp3", song_length=180)
    song11 = Song(title="rockstar", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/rockstar.mp3", song_length=180)
    song12 = Song(title="Psycho", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/psycho.mp3", song_length=180)
    song13 = Song(title="Better Now", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/better-now.mp3", song_length=180)
    song14 = Song(title="Otherside", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/otherside.mp3", song_length=180)
    song15 = Song(title="Candy Paint", album_id = 3, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/candy-paint.mp3", song_length=180)
    song16 = Song(title="Bombtrack", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/bombtrack.mp3", song_length=180)
    song17 = Song(title="Killing in the Name", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/killing-in-the-name.mp3", song_length=180)
    song18 = Song(title="Take the Power Back", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/take-the-power-back.mp3", song_length=180)
    song19 = Song(title="Settle for Nothing", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/settle-for-nothing.mp3", song_length=180)
    song20 = Song(title="Bullet in the Head", album_id = 4, song_url="https://spotify-clone-app.s3-us-west-2.amazonaws.com/bullet-in-the-head.mp3", song_length=180)
    db.session.add(song1)
    db.session.add(song2)
    db.session.add(song3)
    db.session.add(song4)
    db.session.add(song5)
    db.session.add(song6)
    db.session.add(song7)
    db.session.add(song8)
    db.session.add(song9)
    db.session.add(song10)
    db.session.add(song11)
    db.session.add(song12)
    db.session.add(song13)
    db.session.add(song14)
    db.session.add(song15)
    db.session.add(song16)
    db.session.add(song17)
    db.session.add(song18)
    db.session.add(song19)
    db.session.add(song20)
    db.session.commit()
    playlistsong = PlaylistSong(playlist_id=1,song_id=1)
    playlistsong2 = PlaylistSong(playlist_id=1,song_id=2)
    playlistsong3 = PlaylistSong(playlist_id=1,song_id=3)
    playlistsong4 = PlaylistSong(playlist_id=2,song_id=4)
    db.session.add(playlistsong)
    db.session.add(playlistsong2)
    db.session.add(playlistsong3)
    db.session.add(playlistsong4)
    db.session.commit()
